server {
    listen 80;

    # 1. Serve the HTML website to the user
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # 2. Forward API requests to the internal Kubernetes Backend
    location /api/ {
        proxy_pass http://backend-service:8080/;
    }
}